"""init

Revision ID: dd03e0e03b9f
Revises: b2800ed68656
Create Date: 2019-03-12 07:05:48.346789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd03e0e03b9f'
down_revision = 'b2800ed68656'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
